/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChat: typeof import('./src/components/AIChat.vue')['default']
    ArticlePreview: typeof import('./src/components/ArticlePreview.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    CommentBox: typeof import('./src/components/CommentBox.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    NewsSearchCard: typeof import('./src/components/NewsSearchCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
